spring:
  h2:
    console:
        enabled: true
        path: /h2

  datasource:
    url: jdbc:h2:mem:h2db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    jpa:
        show_sql: true
        ddl-auto: none


ibgeLocalidades:
  url: https://servicodados.ibge.gov.br/api/v1/localidades

logging:
  level:
    br.com.openfeign.client.*: DEBUG